## Loading data into pandas

In [86]:
# import pandas as pd

#df = pd.read_csv('pokemon_data.csv')

#print(df.head(3))

# df = pd.read_excel('pokemon_data.xlsx')

# print(df.head(3))

# df = pd.read_csv('pokemon_data.txt', delimiter='\t')

# print(df.head(3))

In [87]:
#print(df.columns)
# df.columns

# print(df[['Name','Type 1','HP']])

# print(df.tail(4))

# print(df.head(4))

In [88]:
import pandas as pd

df = pd.read_csv('students.csv')

df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
1,102,Sara Mehta,25,Female,Delhi,Data Science,92.0,Yes,98
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60
5,106,Priya Nair,20,Female,Chennai,Python,91.0,Yes,99
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,38.0,No,55
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.0,Yes,80
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

In [89]:
# df = pd.read_json('json_sample.json')
# df

# df = pd.read_excel('pokemon_data.xlsx')
# df

In [90]:
# pd.set_option('display.max.rows', 800)
# pd.set_option('display.max.columns', 800)

In [91]:
df = pd.read_csv('students.csv')
df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
1,102,Sara Mehta,25,Female,Delhi,Data Science,92.0,Yes,98
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60
5,106,Priya Nair,20,Female,Chennai,Python,91.0,Yes,99
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,38.0,No,55
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.0,Yes,80
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   20 non-null     int64
 1   Name        20 non-null     object
 2   Age         20 non-null     int64
 3   Gender      20 non-null     object
 4   City        20 non-null     object
 5   Course      20 non-null     object
 6   Marks       19 non-null     float64
 7   Passed      20 non-null     object
 8   Attendance  20 non-null     int64
dtypes: float64(1), int64(3), object(5)
memory usage: 1.5+ KB

In [93]:
df.shape

(20, 9)

In [94]:
df.head(2)

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
1,102,Sara Mehta,25,Female,Delhi,Data Science,92.0,Yes,98

In [95]:
df.tail(2)

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

In [96]:
df['Age']

0     22
1     25
2     21
3     28
4     23
5     20
6     24
7     22
8     27
9     21
10    29
11    24
12    23
13    25
14    30
15    22
16    26
17    23
18    28
19    24
Name: Age, dtype: int64

In [97]:
df.loc[12]

StudentID                  113
Name                Anil Kumar
Age                         23
Gender                    Male
City                     Delhi
Course        Machine Learning
Marks                     79.0
Passed                     Yes
Attendance                  88
Name: 12, dtype: object

## Filtering Columns and Rows in Pandas

In [98]:
import pandas as pd
df = pd.read_csv('students.csv')
df

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
1,102,Sara Mehta,25,Female,Delhi,Data Science,92.0,Yes,98
2,103,John D'souza,21,Male,Bangalore,Python,55.0,No,72
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
4,105,Rahul Verma,23,Male,Pune,Data Science,45.0,No,60
5,106,Priya Nair,20,Female,Chennai,Python,91.0,Yes,99
6,107,Tom Wilson,24,Male,Delhi,Machine Learning,67.0,Yes,78
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
8,109,Arjun Rao,27,Male,Hyderabad,Python,72.0,Yes,82
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,38.0,No,55
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
12,113,Anil Kumar,23,Male,Delhi,Machine Learning,79.0,Yes,88
13,114,Pooja Reddy,25,Female,Hyderabad,Data Science,50.0,No,65
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
15,116,Anjali Iyer,22,Female,Bangalore,Machine Learning,70.0,Yes,80
16,117,Suresh Tiwari,26,Male,Pune,Data Science,NaN,Yes,77
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91
18,119,Vikram Bose,28,Male,Delhi,Machine Learning,63.0,Yes,70
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

In [99]:
df[df['Marks'] >= 80]

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
1,102,Sara Mehta,25,Female,Delhi,Data Science,92.0,Yes,98
5,106,Priya Nair,20,Female,Chennai,Python,91.0,Yes,99
7,108,Neha Gupta,22,Female,Bangalore,Data Science,83.0,Yes,90
10,111,Karan Patel,29,Male,Pune,Data Science,95.0,Yes,97
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91

In [100]:
specific_city = ['Mumbai', 'Chennai']

df[df['City'].isin(specific_city)]

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
5,106,Priya Nair,20,Female,Chennai,Python,91.0,Yes,99
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,38.0,No,55
11,112,Divya Singh,24,Female,Chennai,Python,61.0,Yes,74
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
17,118,Kavya Menon,23,Female,Chennai,Python,88.0,Yes,91
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

In [101]:
df[df['City'].str.contains('m')]

,StudentID,Name,Age,Gender,City,Course,Marks,Passed,Attendance
0,101,Ali Khan,22,Male,Mumbai,Python,88.0,Yes,95
3,104,Mia Sharma,28,Female,Mumbai,Machine Learning,76.0,Yes,85
9,110,Sneha Joshi,21,Female,Mumbai,Machine Learning,38.0,No,55
14,115,Raj Malhotra,30,Male,Mumbai,Python,84.0,Yes,93
19,120,Ritika Shah,24,Female,Mumbai,Data Science,77.0,Yes,86

In [102]:
df = df.set_index('Name')
df

,StudentID,Age,Gender,City,Course,Marks,Passed,Attendance
Name,,,,,,,,
Ali Khan,101,22,Male,Mumbai,Python,88.0,Yes,95
Sara Mehta,102,25,Female,Delhi,Data Science,92.0,Yes,98
John D'souza,103,21,Male,Bangalore,Python,55.0,No,72
Mia Sharma,104,28,Female,Mumbai,Machine Learning,76.0,Yes,85
Rahul Verma,105,23,Male,Pune,Data Science,45.0,No,60
Priya Nair,106,20,Female,Chennai,Python,91.0,Yes,99
Tom Wilson,107,24,Male,Delhi,Machine Learning,67.0,Yes,78
Neha Gupta,108,22,Female,Bangalore,Data Science,83.0,Yes,90
Arjun Rao,109,27,Male,Hyderabad,Python,72.0,Yes,82
Sneha Joshi,110,21,Female,Mumbai,Machine Learning,38.0,No,55
Karan Patel,111,29,Male,Pune,Data Science,95.0,Yes,97
Divya Singh,112,24,Female,Chennai,Python,61.0,Yes,74
Anil Kumar,113,23,Male,Delhi,Machine Learning,79.0,Yes,88
Pooja Reddy,114,25,Female,Hyderabad,Data Science,50.0,No,65
Raj Malhotra,115,30,Male,Mumbai,Python,84.0,Yes,93
Anjali Iyer,116,22,Female,Bangalore,Machine Learning,70.0,Yes,80
Suresh Tiwari,117,26,Male,Pune,Data Science,NaN,Yes,77
Kavya Menon,118,23,Female,Chennai,Python,88.0,Yes,91
Vikram Bose,119,28,Male,Delhi,Machine Learning,63.0,Yes,70
Ritika Shah,120,24,Female,Mumbai,Data Science,77.0,Yes,86

In [103]:
df.filter(items=['Name', 'Course', 'Marks'], axis=1)

                         Course  Marks
Name
Ali Khan                 Python   88.0
Sara Mehta         Data Science   92.0
John D'souza             Python   55.0
Mia Sharma     Machine Learning   76.0
Rahul Verma        Data Science   45.0
Priya Nair               Python   91.0
Tom Wilson     Machine Learning   67.0
Neha Gupta         Data Science   83.0
Arjun Rao                Python   72.0
Sneha Joshi    Machine Learning   38.0
Karan Patel        Data Science   95.0
Divya Singh              Python   61.0
Anil Kumar     Machine Learning   79.0
Pooja Reddy        Data Science   50.0
Raj Malhotra             Python   84.0
Anjali Iyer    Machine Learning   70.0
Suresh Tiwari      Data Science    NaN
Kavya Menon              Python   88.0
Vikram Bose    Machine Learning   63.0
Ritika Shah        Data Science   77.0

In [104]:
df.filter(like= 'A', axis=0)

,StudentID,Age,Gender,City,Course,Marks,Passed,Attendance
Name,,,,,,,,
Ali Khan,101,22,Male,Mumbai,Python,88.0,Yes,95
Arjun Rao,109,27,Male,Hyderabad,Python,72.0,Yes,82
Anil Kumar,113,23,Male,Delhi,Machine Learning,79.0,Yes,88
Anjali Iyer,116,22,Female,Bangalore,Machine Learning,70.0,Yes,80

In [105]:
df = df.set_index('Age')
df
df.loc[22]

     StudentID  Gender       City            Course  Marks Passed  Attendance
Age
22         101    Male     Mumbai            Python   88.0    Yes          95
22         108  Female  Bangalore      Data Science   83.0    Yes          90
22         116  Female  Bangalore  Machine Learning   70.0    Yes          80

In [110]:
df.iloc[0]

StudentID        101
Gender          Male
City          Mumbai
Course        Python
Marks           88.0
Passed           Yes
Attendance        95
Name: 22, dtype: object

In [120]:
df[df['Marks']  <= 70].sort_values(by=['Course', 'Marks'], ascending= [False, True])

     StudentID  Gender       City            Course  Marks Passed  Attendance
Age
21         103    Male  Bangalore            Python   55.0     No          72
24         112  Female    Chennai            Python   61.0    Yes          74
21         110  Female     Mumbai  Machine Learning   38.0     No          55
28         119    Male      Delhi  Machine Learning   63.0    Yes          70
24         107    Male      Delhi  Machine Learning   67.0    Yes          78
22         116  Female  Bangalore  Machine Learning   70.0    Yes          80
23         105    Male       Pune      Data Science   45.0     No          60
25         114  Female  Hyderabad      Data Science   50.0     No          65